apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wireguard-pvc
  labels:
    app: wireguard
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  storageClassName: efs-sc
